# **Principales desafíos** {#principales-desafios}

En la mayoría de las provincias (y/o en municipios) se realiza actualmente, o se ha realizado en algún momento, un estudio sobre el perfil del visitante. No obstante, estos sondeos varían en gran medida en torno a su objeto, unidades bajo estudio, alcance, periodicidad, representatividad estadística de sus resultados y otras cuestiones metodológicas.

En este capítulo se describe en forma general cuáles son las principales problemáticas conceptuales y metodológicas que pueden identificarse. 

Un primer tipo de problema está asociado a la definición de los alcances y/o de los objetivos del estudio que se lleva adelante. En el primer caso, por ejemplo, existen experiencias de encuestas que relevan información sobre un segmento de los visitantes de un destino, asumiendo que éste es representativo del total de visitantes del mismo[^principales_desafios-1]. Asimismo, es posible encontrar estudios cuyos objetivos no concuerdan con la muestra construida, con la cobertura espacio-temporal y/o con la información relevada. En ambos casos, a partir de una atenta reflexión metodológica es posible, o bien definir con mayor precisión estos elementos, o bien, a partir de hacer explícitas las limitaciones, evaluar alternativas para superarlas.

[^principales_desafios-1]: En este caso, la palabra segmento se refiere a un subconjunto de los visitantes definido por la intersección de dos o más variables. Por ejemplo, los turistas (visitantes que pernoctan) que viajan en temporada alta y se alojan en hoteles de las ciudades con mayor afluencia turística de una provincia constituyen un segmento, quizás el más importante desde el punto de vista de su impacto en el gasto turístico total, pero no el único tipo (quizás, ni siquiera el segmento cuantitativamente más numeroso) que conforma el universo de visitantes de una provincia, ya que fuera de este segmento se ubican los excursionistas (visitantes que no pernoctan en el destino), los turistas que no viajan en temporada alta, los turistas que aunque viajan en temporada alta no se alojan en hoteles (es decir, que pernoctan en campings, segundas viviendas, viviendas de familiares, etc.) y los turistas que, aún viajando en temporada alta y alojándose en hoteles, visitan localidades que no son las de mayor afluencia turística de la provincia.

Otro aspecto relevante que afecta tanto a la validez como a la comparabilidad de los resultados está ligado a quién o quiénes representa un encuestado. La definición de visitante, unidad básica de la estadística de turismo, refiere a individuos: un visitante es toda persona que por cualquier motivo (excepto ser empleado en el destino) sale de su entorno habitual por un periodo inferior a un año[^principales_desafios-2]. No obstante, las personas no siempre viajan solas, sino que suelen hacerlo en grupos de visitantes (grupos de viaje[^principales_desafios-3]), es decir acompañados por otras personas que pueden o no ser integrantes de su mismo hogar.

[^principales_desafios-2]: En el Documento Técnico \#1: ***Conceptos y elementos básicos para la medición provincial de los turistas*** se abordan los principales conceptos relativos a la estadística de turismo, en base a definiciones internacionales estandarizadas, y se problematiza acerca de su aplicación desde enfoques subnacionales. En este trabajo se hará mención y/o se desarrollarán sólo aquellos conceptos estrictamente necesarios para introducir discusiones específicas relativas a las encuestas de perfil.

[^principales_desafios-3]: Se entiende por grupo de viaje al conjunto de visitantes que realizan un viaje juntos y que comparten los gastos del mismo. En el apartado 2.2 se profundiza sobre esta cuestión.

En esta línea, los relevamientos provinciales presentan diferencias en torno a las unidades bajo estudio, lo cual dificulta la comparabilidad interprovincial (o intraprovincial) de sus resultados, y, en muchos casos, producto de los sesgos introducidos implícitamente, dan lugar a estimaciones que no corresponden a la realidad. Por ejemplo, se observa cierta confusión entre los grupos de viaje y los individuos como unidades de análisis. Si bien sin excepción las encuestas son respondidas por individuos, estos individuos suelen brindar información como representantes de su grupo de viaje, sin que esto se refleje en el proceso de selección de la muestra, en los cuestionarios aplicados y las fórmulas mediante las cuales se alcanzan los resultados. Éste es sin duda un punto crítico, que conlleva la necesidad de distinguir claramente entre unidad de relevamiento, unidad de análisis e informantes: un individuo responde la encuesta y por tanto es el informante, pero la información que brinda no lo caracteriza sólo a él, sino que podría abarcar a todo su grupo de viaje, y, en realidad, en ese caso, el grupo constituiría la unidad sobre la que se releva información (unidad de relevamiento); no obstante, los resultados o estimaciones que se obtengan del estudio caracterizarán a los visitantes, que, por tanto constituyen la unidad de análisis. Alcanzar este tipo de distinciones no es tarea sencilla, ya que se requiere de planteos conceptuales y metodológicos claros, así como criterios de selección de los casos definidos durante la etapa de relevamiento.

Por otro lado, tanto por la extensión del problema como por la complejidad para lograr soluciones efectivas, la principal dificultad que presentan las encuestas de perfil del visitante se centra en la definición y construcción de una muestra adecuada, que permita obtener resultados estadísticamente válidos. 

Antes de continuar con esta dificultad, es necesario plantear un punto central. En estadística, términos como aleatorio o azar tienen un significado distinto (por no decir radicalmente opuesto) al que usualmente se le asigna desde el sentido común, el cual está relacionado, por ejemplo, a la casualidad. El azar es un concepto fundamental y, a la vez, una condición sumamente difícil de garantizar, pues implica que la selección de los casos que conformarán la muestra no estará influenciada por ningún otro factor ajeno a la probabilidad teórica que cada caso tiene de ser seleccionado. En definitiva, una investigación por muestreo no implica simplemente el estudio de una parte cualquiera (independientemente del tamaño) del universo bajo análisis, sino una selección de casos guiada por criterios que realmente garanticen el azar en la selección: el diseño muestral es la selección de las unidades que conformarán la muestra a partir de la aplicación de las herramientas o técnicas que provee la ciencia estadística. Además, como se verá luego, el tamaño de una muestra, salvo en excepciones, es independiente del tamaño del universo, y está ligado a las características de la población bajo estudio, a la precisión deseada y al nivel de desagregación con que se pretenda analizar los resultados obtenidos. En términos prácticos, por ejemplo, con una muestra de 500 casos se puede caracterizar con la misma precisión tanto al conjunto de turistas que visitan Mar del Plata como al conjunto de turistas que arriban a una pequeña localidad balnearia, como por ejemplo, Claromecó.

En este punto, para lograr un buen diseño muestral resulta crucial contar con un marco muestral (o al menos una aproximación razonable), desde el cual seleccionar una muestra que represente al universo o población que se pretende estudiar. El marco muestral constituye el elemento central para la realización de un estudio estadísticamente representativo: aporta la ubicación espacial y temporal del universo bajo análisis y, en términos ideales, asume la forma de un listado donde constan todas las unidades que constituyen el universo y a partir de donde se extraerán en forma aleatoria las unidades que formarán parte de la muestra. El problema es, en términos de teoría de muestreo, garantizar que todas las unidades tengan probabilidad de ser seleccionadas para integrar la muestra, y que la probabilidad de selección de cada unidad sea conocida, derivada del diseño muestral[^principales_desafios-4].

[^principales_desafios-4]: En una muestra aleatoria simple, donde se selecciona al azar un conjunto de casos, la probabilidad de selección es la misma para cada una de las unidades. En cambio, en las muestras complejas, la probabilidad de selección de los casos usualmente varía entre los elementos, respondiendo ello a necesidades derivadas de los objetivos de la investigación o a estrategias para aumentar la eficiencia de la muestra.

A diferencia de los estudios de ocupación en alojamientos turísticos, por ejemplo, en donde se suele disponer de un listado de establecimientos que permite conocer de antemano el universo (y, por tanto, seleccionar una muestra en forma aleatoria) y constituye el marco muestral de la investigación, en las encuestas de perfil, donde se pretende obtener información indagando directamente al visitante en el lugar de destino, resulta lógicamente imposible contar con un listado de visitantes que arriben al destino bajo estudio en un periodo determinado. Este problema emerge no sólo de la presencia o no de recursos técnicos o económicos en cada equipo productor de estadística de turismo, sino del propio visitante como objeto de estudio. Claramente, resulta imposible enumerar o listar a todos los visitantes de un destino y luego sortear a aquellos que serán encuestados. Del mismo modo, los visitantes (o al menos una gran parte de ellos) no son claramente identificables ni realizan todos las mismas actividades o recorridos[^principales_desafios-5]. Por ello, en estos casos el diseño muestral y las instrucciones que de él se deriven para el trabajo de campo, son centrales, pues requieren implementar estrategias de selección aleatoria de unidades innovadoras y que no invaliden la pretensión de representatividad estadística del estudio. En este sentido, la construcción de aproximaciones a marcos muestrales adecuados y el diseño de la muestra (los criterios que se aplicarán para la selección de los casos a encuestar) resultan, en general, más importante aún que la discusión acerca del tamaño de la muestra.

[^principales_desafios-5]: En cambio, en las encuestas a hogares destinadas a cuantificar y caracterizar la demanda turística (como la EVyTH en el caso argentino, cuyas principales características se reseñan en la sección siguiente) sí es posible construir marcos muestrales convencionales (listado de viviendas u hogares).

Respecto a este último punto, el tamaño de la muestra, la teoría del muestreo aporta elementos que, simplificados, permiten estimar de manera relativamente sencilla cuál debe ser el tamaño de muestra adecuado a los objetivos del estudio. No obstante, la reflexión sobre la relación entre objetivos de estudio y tamaño muestral suele estar ausente. Así, en ciertos operativos se releva una cantidad de casos sustancialmente superior a la necesaria para dar cuenta de los objetivos propuestos, mientras que en otros, contrariamente, resulta evidente que el tamaño muestral es exiguo para la profundidad analítica que procuran los objetivos. Por ejemplo, una muestra relativamente chica (400 o 500 casos), permite alcanzar resultados básicos (distribución de frecuencias de las variables para un conjunto acotado de categorías; por ejemplo, distribución de los turistas según lugar de residencia en la misma provincia, en el resto del país o en el exterior) con una precisión razonable; pero, en general, no alcanza para obtener resultados estadísticamente robustos en los cruces entre variables (por ejemplo, distribución de los turistas de cada origen según tipo de alojamiento utilizado) ni para realizar comparaciones entre resultados de estudios cercanos en el tiempo (pues las variaciones en los resultados, salvo situaciones excepcionales, se ubicaran dentro de los márgenes de error de ambas estimaciones, lo que implica que no pueden establecerse diferencias estadísticamente significativas). Claro está que el tamaño de la muestra no puede determinarse únicamente en función de los objetivos deseados, sino que debe ser viable, en términos de haber considerado las restricciones habituales de recursos (técnicos, económicos, etc.).

Lógicamente, un aspecto crucial en la construcción metodológica de una encuesta de perfil es la elaboración del cuestionario, que implica determinar qué variables serán relevadas y de qué modo se operacionalizará[^principales_desafios-6] su definición y, concomitantemente, qué sistema de categorías se utilizará. Por ejemplo, la variable duración de la estadía debe ser definida en términos concretos (por ejemplo, cantidad de noches de alojamiento en el destino) y debe traducirse en una pregunta (o varias, depende el caso) de fácil comprensión para el entrevistado. Del mismo modo, las categorías u opciones de respuesta deben ser claras para quien responde, y, además, acotadas en número para no complejizar el trabajo del encuestador. De esta manera, además, se asegura la obtención de información relevante evitando la incorporación de datos innecesarios que en muchas ocasiones, por el tamaño de la muestra, impiden la desagregación de la información relevada con altos niveles de especificidad. Como se observa, nuevamente, es preciso un ajuste o consistencia entre objetivos, diseño muestral e información a relevar.

[^principales_desafios-6]: La operacionalización es el proceso metodológico mediante el cual conceptos complejos se hacen medibles. Por ejemplo, si se busca clasificar a las personas según su nivel socioeconómico, no se preguntará directamente por lo que el informante considera que es su nivel socioeconómico, sino que se le realizarán preguntas sencillas sobre un conjunto de cuestiones concretas (ingresos monetarios, tenencia de distintos bienes, nivel educativo, etc.) a partir del cual se determinará, en base a la definición adoptada, en qué nivel socioeconómico se ubica.

La definición de las variables debe ser sumamente clara, y basada, en la medida de lo posible, en la bibliografía disponible y reconocida (como las recomendaciones de la Organización Mundial de Turismo --OMT-) y en las buenas experiencias existentes, tanto a nivel local, como nacional o internacional. Cabe señalar que sólo la definición explícita de las variables y sus categorías permitirá evaluar su comparabilidad respecto a otros estudios, lo que, en el marco de la búsqueda de armonización de la estadística de turismo en el país, resulta un desafío no menor.

Un aspecto fundamental que habitualmente no es abordado por las encuestas de perfil del visitante es, precisamente, la definición y operacionalización del concepto de visitante. La OMT (RIET, 2008) define que "el turismo es la actividad propia de los visitantes" y aporta elementos generales para su identificación, entre los que destaca el concepto de entorno habitual. No operacionalizar estos conceptos (a través de instrucciones al personal de campo y de preguntas en el formulario) implica recortar el universo incorrectamente o, al menos, de una forma alejada de las sugerencias de las recomendaciones internacionales. Más aún, la ausencia de este tipo de definiciones conlleva en general la imposibilidad de determinar con precisión el objeto de estudio, que aparece difuminado y más cerca de lo que se entiende por turismo desde el sentido común que desde lo que técnicamente debiera ser.

Una de las variables centrales en los formularios utilizados en las investigaciones de caracterización de la demanda es el gasto turístico, ya sea que se trate del gasto promedio por turista/excursionista o del gasto diario promedio. En primer lugar, es necesario fijar con claridad cómo se define y se compone el gasto turístico, para lo cual, por suerte, existe abundante bibliografía.

Adicionalmente, el relevamiento del gasto en destino (provincia o localidad), enfoque adoptado en la mayoría de las encuestas de perfil provinciales/municipales, supone un nivel de dificultad extra, en la definición tanto del período de referencia del gasto (día anterior, toda la estadía en el destino, días que lleva en el destino, etc.) como del sujeto sobre el que se relevará la información (informante o grupo de viaje). En este punto, la medición del gasto en transporte desde y hacia el destino, como también la decisión acerca de si debe (y en qué proporción) o no ser computado desde el enfoque provincial, constituye un desafío por sí mismo).

Finalmente, es preciso delinear estrategias adecuadas para la captación del gasto, ya sea a nivel agregado (el gasto total) o por producto (alojamiento, alimentación, etc.), y estas estrategias deberán ser acordes a las características y limitaciones del trabajo de campo.

Un aspecto crucial, debido a la repetición del problema y a los efectos que acarrea, está ligado a la fórmula de cálculo del gasto. Es común que el gasto diario promedio por turista sea calculado a partir del promedio simple del valor estimado para cada encuestado, sin tomar en cuenta el tamaño de su grupo de viaje ni la duración de la estadía. Ello conlleva una sobreestimación del valor de este indicador, ya que de esta forma se sobredimensiona el peso de quienes viajan en pequeños grupos y/o por un breve lapso de tiempo, que son quienes, en general, presentan los mayores niveles de gasto diario promedio.

El problema radica no sólo en que el dato estimado es matemáticamente incorrecto (y, por tanto, falso), sino que en ocasiones es utilizado como insumo para la estimación del gasto turístico total registrado en un destino (donde intervienen otros elementos, como la cantidad de visitantes, dato que en general surge de otra fuente, y la estadía promedio, que usualmente también se deriva del estudio de perfil del visitante, y cuyo cálculo también suele presentar sesgos que inducen al error). Por consiguiente, al tomar insumos erróneamente estimados, el resultado global al que se arribará carecerá también de validez.

En definitiva, cómo toda investigación, la mejor encuesta de perfil del visitante no es aquella que presenta los objetivos más interesantes o novedosos, ni aquella que alcanza la mayor cobertura territorial y/o temporal, tampoco la que releva una mayor cantidad de casos ni la que incluye una gran cantidad de variables en sus formularios: **la mejor encuesta es la que logra una relación equilibrada y eficiente entre todos estos elementos**, siempre en el marco de un conocimiento cabal de las potencialidades y las restricciones del contexto (presupuesto, recursos técnicos, etc.), como ya se mencionó anteriormente.

Luego de un breve repaso sobre las dos encuestas de perfil del visitante llevadas a cabo actualmente por el Ministerio de Turismo y Deportes de la Nación, en el **capítulo 3** se presentan elementos y propuestas que procuran contribuir la construcción de investigaciones que alcancen esta **armonía** y que, a su vez, se basen en metodologías estandarizadas que permitan obtener resultados comparables.
