---
title: "Documento Técnico N°4: Encuestas a Visitantes"
subtitle: "Propuestas Metodológicas para las Encuestas de Perfil del Visitante"
author: "Dirección Nacional de Mercados y Estadísticas -  Subsecretaría de Desarrollo Estratégico"
date: "`r format(Sys.Date(), format = '%d de %B de %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Propuestas Metodológicas para las Encuestas de Perfil del Visitante"
---

# **Presentación** {.unnumbered}

El presente documento **Propuestas Metodológicas para las Encuestas de Perfil del Visitante** se enmarca en el proyecto de *Armonización de las Estadísticas de Turismo en las Provincias* de la [Dirección Nacional de Mercados y Estadística de la Subsecretaría de Desarrollo Estratégico del Ministerio de Turismo y Deportes](http://datos.yvera.gob.ar/). El objetivo general de este proyecto es contribuir con propuestas metodológicas para los sistemas de estadísticas de turismo provinciales que orienten a producir indicadores provinciales básicos y comparables.

Además de este, se encuentran disponibles una serie de documentos técnicos que abordan otras problemáticas vinculadas a la producción de estadística de turismo:

-   [Documento Técnico \#1](https://dnme-minturdep.github.io/DT1_medicion_turismo/): Conceptos y elementos básicos para la medición provincial de los turistas

-   [Documento Técnico \#2](https://dnme-minturdep.github.io/DT2_encuestas/): Propuestas metodológicas para las encuestas de ocupación en alojamientos turísticos

-   [Documento Técnico \#3](https://dnme-minturdep.github.io/DT3_registros_adminsitrativos/): Descripción, análisis y utilización de los Registros Administrativos para la medición del Turismo

-   Documento Técnico \#5: Medición de la contribución económica del turismo: actividad y empleo

### Documento Técnico Nº4 - Resumen {.unnumbered}

Los estudios de caracterización de la demanda turística o de perfil del visitante[^index-1] (turista y/o excursionista) constituyen un insumo esencial a la hora de conocer las características de los visitantes que arriban a un destino (sea un país, una provincia, un municipio o una localidad) y monitorear su evolución, aportando herramientas para la generación y gestión de políticas públicas relativas al turismo. Adicionalmente, constituyen una fuente de información privilegiada para analizar el gasto turístico que realizan los diferentes tipos de visitantes, sirviendo como insumo para la estimación del impacto económico de la actividad.

[^index-1]: Ambos términos se utilizarán de forma indistinta en este documento.

En este contexto, este documento técnico tiene el propósito de brindar un panorama general sobre los principales desafíos que se presentan para la realización exitosa de este tipo de investigaciones, como así también generar propuestas que permitan fortalecer los estudios de demanda turística o perfil del visitante, procurando aportar al desarrollo de estándares básicos de calidad y comparabilidad de la información. Estas propuestas constituyen herramientas básicas para el diseño de investigaciones de este tipo, con varios objetivos simultáneos: fortalecer la capacidad técnica de los equipos de estadística de turismo para diseñar e implementar encuestas de caracterización de la demanda, brindar herramientas para el análisis crítico de su propia producción o de investigaciones presentes o futuras realizadas por otros organismos (empresas contratadas para tal fin por el ente provincial o municipal, universidades y centros de estudio, cámaras del sector, etc.) y contribuir a un proceso de estandarización nacional de las metodologías aplicadas.

En virtud de estos objetivos, este documento se estructura en tres capítulos.

El **Capítulo** \@ref(principales-desafios) describe los principales desafíos metodológicos en los estudios de perfil relevados en todo el país.

El **Capítulo** \@ref(encuestas-nacionales-de-perfil) presenta la experiencia del Ministerio de Turismo y Deportes en sus relevamientos de perfil de visitante interno e internacional.\
\
El **Capítulo** \@ref(propuestas-metodologicas) aborda en detalle los puntos críticos involucrados en este tipo de estudios, presentando propuestas conceptuales y metodológicas que permitan superarlos. 

Finalmente, en los **Anexos** se presentan dos modelos de cuestionarios, que fueron elaborados en versiones genéricas, para servir como referencia en los estudios de perfil del visitante a niveles subnacionales.

Cabe señalar que este documento de trabajo realiza un recorrido por aspectos cuya complejidad no es menor. Por otro lado, si bien todas las etapas de una investigación están interrelacionadas, se ha procurado seguir un orden lógico, aunque en ciertos casos se ha privilegiado desarrollar en profundidad algunos temas, lo que ha implicado trasponer el orden lógico de algunas de las etapas. 

Por tanto, se sugiere que se realice una (o más de una) lectura atenta y profunda, no sólo para comprender ciertas cuestiones que se tratan, sino también para identificar los aspectos más relevantes a la hora de emprender la puesta en marcha de estudios de este tipo y poder abonar críticamente a la construcción colectiva.
